export const rowsList = [
  {
    title: 'Vinfast',
    id: '1425',
    created_date: '20-10-2016',
    description:
      'VinFast is a private automotive startup manufacturer headquartered in Vietnam, a member of Vingroup which is one of the largest private enterprises in the country.',
    contact: 'Linhdam, Hoangmai, Hanoi',
    phone: '0987489732',
    product: 'Car',
    email: 'kiendc@lifetek.vn',
    action: 'DEL',
    status: 0,
  },
  {
    title: 'Apple',
    id: '1253',
    created_date: '09-12-2014',
    description:
      'Apple Inc. is an American multinational technology company headquartered in Cupertino, California, that designs, develops, and sells consumer electronics, computer software, and online services. It is considered one of the Big Four of technology along with Amazon, Google, and Facebook',
    contact: '1 Apple Park Way, Cupertino, California, U.S.',
    phone: '0987489543',
    product: 'Phone',
    email: 'contact@apple.com',
    action: 'DEL',
    status: 1,
  },
  {
    title: 'Samsung',
    id: '1266',
    created_date: '09-12-2014',
    description:
      'Apple Inc. is an American multinational technology company headquartered in Cupertino, California, that designs, develops, and sells consumer electronics, computer software, and online services. It is considered one of the Big Four of technology along with Amazon, Google, and Facebook',
    contact: '1 Apple Park Way, Cupertino, California, U.S.',
    phone: '0987489543',
    product: 'Phone',
    email: 'contact@apple.com',
    action: 'DEL',
    status: 2,
  },
  {
    title: 'Lifetek',
    id: '1276',
    created_date: '09-12-2014',
    description:
      'Apple Inc. is an American multinational technology company headquartered in Cupertino, California, that designs, develops, and sells consumer electronics, computer software, and online services. It is considered one of the Big Four of technology along with Amazon, Google, and Facebook',
    contact: '1 Apple Park Way, Cupertino, California, U.S.',
    phone: '0987489543',
    product: 'Phone',
    email: 'contact@apple.com',
    action: 'DEL',
    status: 1,
  },
  {
    title: 'Dell',
    id: '129',
    created_date: '09-12-2014',
    description:
      'Apple Inc. is an American multinational technology company headquartered in Cupertino, California, that designs, develops, and sells consumer electronics, computer software, and online services. It is considered one of the Big Four of technology along with Amazon, Google, and Facebook',
    contact: '1 Apple Park Way, Cupertino, California, U.S.',
    phone: '0987489543',
    product: 'Phone',
    email: 'contact@apple.com',
    action: 'DEL',
    status: 0,
  },
  {
    title: 'Microsoft',
    id: '128',
    created_date: '09-12-2014',
    description:
      'Apple Inc. is an American multinational technology company headquartered in Cupertino, California, that designs, develops, and sells consumer electronics, computer software, and online services. It is considered one of the Big Four of technology along with Amazon, Google, and Facebook',
    contact: '1 Apple Park Way, Cupertino, California, U.S.',
    phone: '0987489543',
    product: 'Phone',
    email: 'contact@apple.com',
    action: 'DEL',
    status: 0,
  },
  {
    title: 'Apple',
    id: '127',
    created_date: '09-12-2014',
    description:
      'Apple Inc. is an American multinational technology company headquartered in Cupertino, California, that designs, develops, and sells consumer electronics, computer software, and online services. It is considered one of the Big Four of technology along with Amazon, Google, and Facebook',
    contact: '1 Apple Park Way, Cupertino, California, U.S.',
    phone: '0987489543',
    product: 'Phone',
    email: 'contact@apple.com',
    action: 'DEL',
    status: 2,
  },
  {
    title: 'Yahoo',
    id: '126',
    created_date: '09-12-2014',
    description:
      'Apple Inc. is an American multinational technology company headquartered in Cupertino, California, that designs, develops, and sells consumer electronics, computer software, and online services. It is considered one of the Big Four of technology along with Amazon, Google, and Facebook',
    contact: '1 Apple Park Way, Cupertino, California, U.S.',
    phone: '0987489543',
    product: 'Phone',
    email: 'contact@apple.com',
    action: 'DEL',
    status: 1,
  },
  {
    title: 'Fabook',
    id: '125',
    created_date: '09-12-2014',
    description:
      'Apple Inc. is an American multinational technology company headquartered in Cupertino, California, that designs, develops, and sells consumer electronics, computer software, and online services. It is considered one of the Big Four of technology along with Amazon, Google, and Facebook',
    contact: '1 Apple Park Way, Cupertino, California, U.S.',
    phone: '0987489543',
    product: 'Phone',
    email: 'contact@apple.com',
    action: 'DEL',
    status: 1,
  },
  {
    title: 'Github',
    id: '8124',
    created_date: '09-12-2014',
    description:
      'Apple Inc. is an American multinational technology company headquartered in Cupertino, California, that designs, develops, and sells consumer electronics, computer software, and online services. It is considered one of the Big Four of technology along with Amazon, Google, and Facebook',
    contact: '1 Apple Park Way, Cupertino, California, U.S.',
    phone: '0987489543',
    product: 'Phone',
    email: 'contact@apple.com',
    action: 'DEL',
    status: 0,
  },
  {
    title: 'Youtube',
    id: '1727',
    created_date: '09-12-2014',
    description:
      'Apple Inc. is an American multinational technology company headquartered in Cupertino, California, that designs, develops, and sells consumer electronics, computer software, and online services. It is considered one of the Big Four of technology along with Amazon, Google, and Facebook',
    contact: '1 Apple Park Way, Cupertino, California, U.S.',
    phone: '0987489543',
    product: 'Phone',
    email: 'contact@apple.com',
    action: 'DEL',
    status: 1,
  },
  {
    title: 'Toyota',
    id: '7126',
    created_date: '09-12-2014',
    description:
      'Apple Inc. is an American multinational technology company headquartered in Cupertino, California, that designs, develops, and sells consumer electronics, computer software, and online services. It is considered one of the Big Four of technology along with Amazon, Google, and Facebook',
    contact: '1 Apple Park Way, Cupertino, California, U.S.',
    phone: '0987489543',
    product: 'Phone',
    email: 'contact@apple.com',
    action: 'DEL',
    status: 1,
  },
  {
    title: 'Tiki',
    id: '2125',
    created_date: '09-12-2014',
    description:
      'Apple Inc. is an American multinational technology company headquartered in Cupertino, California, that designs, develops, and sells consumer electronics, computer software, and online services. It is considered one of the Big Four of technology along with Amazon, Google, and Facebook',
    contact: '1 Apple Park Way, Cupertino, California, U.S.',
    phone: '0987489543',
    product: 'Phone',
    email: 'contact@apple.com',
    action: 'DEL',
    status: 1,
  },
  {
    title: 'Amazon',
    id: '12434',
    created_date: '09-12-2014',
    description:
      'Apple Inc. is an American multinational technology company headquartered in Cupertino, California, that designs, develops, and sells consumer electronics, computer software, and online services. It is considered one of the Big Four of technology along with Amazon, Google, and Facebook',
    contact: '1 Apple Park Way, Cupertino, California, U.S.',
    phone: '0987489543',
    product: 'Phone',
    email: 'contact@apple.com',
    action: 'DEL',
    status: 1,
  },
  {
    title: 'Honda',
    id: '457126',
    created_date: '09-12-2014',
    description:
      'Apple Inc. is an American multinational technology company headquartered in Cupertino, California, that designs, develops, and sells consumer electronics, computer software, and online services. It is considered one of the Big Four of technology along with Amazon, Google, and Facebook',
    contact: '1 Apple Park Way, Cupertino, California, U.S.',
    phone: '0987489543',
    product: 'Phone',
    email: 'contact@apple.com',
    action: 'DEL',
    status: 1,
  },
  {
    title: 'Mazada',
    id: '52425',
    created_date: '09-12-2014',
    description:
      'Apple Inc. is an American multinational technology company headquartered in Cupertino, California, that designs, develops, and sells consumer electronics, computer software, and online services. It is considered one of the Big Four of technology along with Amazon, Google, and Facebook',
    contact: '1 Apple Park Way, Cupertino, California, U.S.',
    phone: '0987489543',
    product: 'Phone',
    email: 'contact@apple.com',
    action: 'DEL',
    status: 1,
  },
  {
    title: 'Sony',
    id: '21434',
    created_date: '09-12-2014',
    description:
      'Apple Inc. is an American multinational technology company headquartered in Cupertino, California, that designs, develops, and sells consumer electronics, computer software, and online services. It is considered one of the Big Four of technology along with Amazon, Google, and Facebook',
    contact: '1 Apple Park Way, Cupertino, California, U.S.',
    phone: '0987489543',
    product: 'Phone',
    email: 'contact@apple.com',
    action: 'DEL',
    status: 2,
  },
  {
    title: 'Asus',
    id: '71',
    created_date: '09-12-2014',
    description:
      'Apple Inc. is an American multinational technology company headquartered in Cupertino, California, that designs, develops, and sells consumer electronics, computer software, and online services. It is considered one of the Big Four of technology along with Amazon, Google, and Facebook',
    contact: '1 Apple Park Way, Cupertino, California, U.S.',
    phone: '0987489543',
    product: 'Phone',
    email: 'contact@apple.com',
    action: 'DEL',
    status: 1,
  },
  {
    title: 'Intel',
    id: '21',
    created_date: '09-12-2014',
    description:
      'Apple Inc. is an American multinational technology company headquartered in Cupertino, California, that designs, develops, and sells consumer electronics, computer software, and online services. It is considered one of the Big Four of technology along with Amazon, Google, and Facebook',
    contact: '1 Apple Park Way, Cupertino, California, U.S.',
    phone: '0987489543',
    product: 'Phone',
    email: 'contact@apple.com',
    action: 'DEL',
    status: 1,
  },
  {
    title: 'Valve',
    id: '12',
    created_date: '09-12-2014',
    description:
      'Apple Inc. is an American multinational technology company headquartered in Cupertino, California, that designs, develops, and sells consumer electronics, computer software, and online services. It is considered one of the Big Four of technology along with Amazon, Google, and Facebook',
    contact: '1 Apple Park Way, Cupertino, California, U.S.',
    phone: '0987489543',
    product: 'Phone',
    email: 'contact@apple.com',
    action: 'DEL',
    status: 1,
  },
  {
    title: 'Viettel',
    id: '45',
    created_date: '09-12-2014',
    description:
      'Apple Inc. is an American multinational technology company headquartered in Cupertino, California, that designs, develops, and sells consumer electronics, computer software, and online services. It is considered one of the Big Four of technology along with Amazon, Google, and Facebook',
    contact: '1 Apple Park Way, Cupertino, California, U.S.',
    phone: '0987489543',
    product: 'Phone',
    email: 'contact@apple.com',
    action: 'DEL',
    status: 1,
  },
  {
    title: 'Vietcombank',
    id: '52',
    created_date: '09-12-2014',
    description:
      'Apple Inc. is an American multinational technology company headquartered in Cupertino, California, that designs, develops, and sells consumer electronics, computer software, and online services. It is considered one of the Big Four of technology along with Amazon, Google, and Facebook',
    contact: '1 Apple Park Way, Cupertino, California, U.S.',
    phone: '0987489543',
    product: 'Phone',
    email: 'contact@apple.com',
    action: 'DEL',
    status: 1,
  },
  {
    title: 'BIDV',
    id: '21',
    created_date: '09-12-2014',
    description:
      'Apple Inc. is an American multinational technology company headquartered in Cupertino, California, that designs, develops, and sells consumer electronics, computer software, and online services. It is considered one of the Big Four of technology along with Amazon, Google, and Facebook',
    contact: '1 Apple Park Way, Cupertino, California, U.S.',
    phone: '0987489543',
    product: 'Phone',
    email: 'contact@apple.com',
    action: 'DEL',
    status: 2,
  },
];

export const columnsList = [
  { name: 'title', title: 'Cơ hội kinh doanh', visibility: true },
  { name: 'created_date', title: 'Đã tạo', visibility: true },
  { name: 'contact', title: 'Liên hệ', visibility: true },
  { name: 'phone', title: 'SĐT', visibility: true },
  { name: 'email', title: 'Email', visibility: true },
  { name: 'product', title: 'Sản phẩm/ Dịch vụ', visibility: false },
  { name: 'action', title: 'Hành động', visibility: true },
  { name: 'status', title: 'Trạng thái', visibility: true },
];

// Trao đổi thỏa thuận

export const tradingList = [
  {
    title: 'Vinfast',
    id: '1425',
    created_date: '20-10-2016',
    description:
      'VinFast is a private automotive startup manufacturer headquartered in Vietnam, a member of Vingroup which is one of the largest private enterprises in the country.',
    contact: 'Linhdam, Hoangmai, Hanoi',
    phone: '0987489732',
    email: 'kiendc@lifetek.vn',
    action: 'DEL',
    status: 0,
    budget: 426,
    focal: 'Nguyễn Thu Lan',
    fees: 202,
    inCharge: 'Nguyễn Mạnh Trường',
  },
  {
    title: 'Apple',
    id: '1253',
    created_date: '09-12-2014',
    description:
      'Apple Inc. is an American multinational technology company headquartered in Cupertino, California, that designs, develops, and sells consumer electronics, computer software, and online services. It is considered one of the Big Four of technology along with Amazon, Google, and Facebook',
    contact: '1 Apple Park Way, Cupertino, California, U.S.',
    phone: '0987489543',
    email: 'contact@apple.com',
    action: 'DEL',
    status: 1,
    budget: 426,
    focal: 'Nguyễn Thu Lan',
    fees: 202,
    inCharge: 'Nguyễn Mạnh Trường',
  },
  {
    title: 'Samsung',
    id: '1266',
    created_date: '09-12-2014',
    description:
      'Apple Inc. is an American multinational technology company headquartered in Cupertino, California, that designs, develops, and sells consumer electronics, computer software, and online services. It is considered one of the Big Four of technology along with Amazon, Google, and Facebook',
    contact: '1 Apple Park Way, Cupertino, California, U.S.',
    phone: '0987489543',
    email: 'contact@apple.com',
    action: 'DEL',
    status: 2,
    budget: 426,
    focal: 'Nguyễn Thu Lan',
    fees: 202,
    inCharge: 'Nguyễn Mạnh Trường',
  },
  {
    title: 'Lifetek',
    id: '1276',
    created_date: '09-12-2014',
    description:
      'Apple Inc. is an American multinational technology company headquartered in Cupertino, California, that designs, develops, and sells consumer electronics, computer software, and online services. It is considered one of the Big Four of technology along with Amazon, Google, and Facebook',
    contact: '1 Apple Park Way, Cupertino, California, U.S.',
    phone: '0987489543',
    email: 'contact@apple.com',
    action: 'DEL',
    status: 1,
    budget: 426,
    focal: 'Nguyễn Thu Lan',
    fees: 202,
    inCharge: 'Nguyễn Mạnh Trường',
  },
  {
    title: 'Dell',
    id: '129',
    created_date: '09-12-2014',
    description:
      'Apple Inc. is an American multinational technology company headquartered in Cupertino, California, that designs, develops, and sells consumer electronics, computer software, and online services. It is considered one of the Big Four of technology along with Amazon, Google, and Facebook',
    contact: '1 Apple Park Way, Cupertino, California, U.S.',
    phone: '0987489543',
    email: 'contact@apple.com',
    action: 'DEL',
    status: 0,
    budget: 426,
    focal: 'Nguyễn Thu Lan',
    fees: 202,
    inCharge: 'Nguyễn Mạnh Trường',
  },
  {
    title: 'Microsoft',
    id: '128',
    created_date: '09-12-2014',
    description:
      'Apple Inc. is an American multinational technology company headquartered in Cupertino, California, that designs, develops, and sells consumer electronics, computer software, and online services. It is considered one of the Big Four of technology along with Amazon, Google, and Facebook',
    contact: '1 Apple Park Way, Cupertino, California, U.S.',
    phone: '0987489543',
    email: 'contact@apple.com',
    action: 'DEL',
    status: 0,
    budget: 426,
    focal: 'Nguyễn Thu Lan',
    fees: 202,
    inCharge: 'Nguyễn Mạnh Trường',
  },
  {
    title: 'Apple',
    id: '127',
    created_date: '09-12-2014',
    description:
      'Apple Inc. is an American multinational technology company headquartered in Cupertino, California, that designs, develops, and sells consumer electronics, computer software, and online services. It is considered one of the Big Four of technology along with Amazon, Google, and Facebook',
    contact: '1 Apple Park Way, Cupertino, California, U.S.',
    phone: '0987489543',
    email: 'contact@apple.com',
    action: 'DEL',
    status: 2,
    budget: 426,
    focal: 'Nguyễn Thu Lan',
    fees: 202,
    inCharge: 'Nguyễn Mạnh Trường',
  },
  {
    title: 'Yahoo',
    id: '126',
    created_date: '09-12-2014',
    description:
      'Apple Inc. is an American multinational technology company headquartered in Cupertino, California, that designs, develops, and sells consumer electronics, computer software, and online services. It is considered one of the Big Four of technology along with Amazon, Google, and Facebook',
    contact: '1 Apple Park Way, Cupertino, California, U.S.',
    phone: '0987489543',
    email: 'contact@apple.com',
    action: 'DEL',
    status: 0,
    budget: 426,
    focal: 'Nguyễn Thu Lan',
    fees: 202,
    inCharge: 'Nguyễn Mạnh Trường',
  },
  {
    title: 'Fabook',
    id: '125',
    created_date: '09-12-2014',
    description:
      'Apple Inc. is an American multinational technology company headquartered in Cupertino, California, that designs, develops, and sells consumer electronics, computer software, and online services. It is considered one of the Big Four of technology along with Amazon, Google, and Facebook',
    contact: '1 Apple Park Way, Cupertino, California, U.S.',
    phone: '0987489543',
    email: 'contact@apple.com',
    action: 'DEL',
    status: 1,
    budget: 426,
    focal: 'Nguyễn Thu Lan',
    fees: 202,
    inCharge: 'Nguyễn Mạnh Trường',
  },
  {
    title: 'Github',
    id: '8124',
    created_date: '09-12-2014',
    description:
      'Apple Inc. is an American multinational technology company headquartered in Cupertino, California, that designs, develops, and sells consumer electronics, computer software, and online services. It is considered one of the Big Four of technology along with Amazon, Google, and Facebook',
    contact: '1 Apple Park Way, Cupertino, California, U.S.',
    phone: '0987489543',
    email: 'contact@apple.com',
    action: 'DEL',
    status: 0,
    budget: 426,
    focal: 'Nguyễn Thu Lan',
    fees: 202,
    inCharge: 'Nguyễn Mạnh Trường',
  },
  {
    title: 'Youtube',
    id: '1727',
    created_date: '09-12-2014',
    description:
      'Apple Inc. is an American multinational technology company headquartered in Cupertino, California, that designs, develops, and sells consumer electronics, computer software, and online services. It is considered one of the Big Four of technology along with Amazon, Google, and Facebook',
    contact: '1 Apple Park Way, Cupertino, California, U.S.',
    phone: '0987489543',
    email: 'contact@apple.com',
    action: 'DEL',
    status: 0,
    budget: 426,
    focal: 'Nguyễn Thu Lan',
    fees: 202,
    inCharge: 'Nguyễn Mạnh Trường',
  },
  {
    title: 'Toyota',
    id: '7126',
    created_date: '09-12-2014',
    description:
      'Apple Inc. is an American multinational technology company headquartered in Cupertino, California, that designs, develops, and sells consumer electronics, computer software, and online services. It is considered one of the Big Four of technology along with Amazon, Google, and Facebook',
    contact: '1 Apple Park Way, Cupertino, California, U.S.',
    phone: '0987489543',
    email: 'contact@apple.com',
    action: 'DEL',
    status: 1,
    budget: 426,
    focal: 'Nguyễn Thu Lan',
    fees: 202,
    inCharge: 'Nguyễn Mạnh Trường',
  },
  {
    title: 'Tiki',
    id: '2125',
    created_date: '09-12-2014',
    description:
      'Apple Inc. is an American multinational technology company headquartered in Cupertino, California, that designs, develops, and sells consumer electronics, computer software, and online services. It is considered one of the Big Four of technology along with Amazon, Google, and Facebook',
    contact: '1 Apple Park Way, Cupertino, California, U.S.',
    phone: '0987489543',
    email: 'contact@apple.com',
    action: 'DEL',
    status: 1,
    budget: 426,
    focal: 'Nguyễn Thu Lan',
    fees: 202,
    inCharge: 'Nguyễn Mạnh Trường',
  },
  {
    title: 'Amazon',
    id: '12434',
    created_date: '09-12-2014',
    description:
      'Apple Inc. is an American multinational technology company headquartered in Cupertino, California, that designs, develops, and sells consumer electronics, computer software, and online services. It is considered one of the Big Four of technology along with Amazon, Google, and Facebook',
    contact: '1 Apple Park Way, Cupertino, California, U.S.',
    phone: '0987489543',
    email: 'contact@apple.com',
    action: 'DEL',
    status: 0,
    budget: 426,
    focal: 'Nguyễn Thu Lan',
    fees: 202,
    inCharge: 'Nguyễn Mạnh Trường',
  },
  {
    title: 'Honda',
    id: '457126',
    created_date: '09-12-2014',
    description:
      'Apple Inc. is an American multinational technology company headquartered in Cupertino, California, that designs, develops, and sells consumer electronics, computer software, and online services. It is considered one of the Big Four of technology along with Amazon, Google, and Facebook',
    contact: '1 Apple Park Way, Cupertino, California, U.S.',
    phone: '0987489543',
    email: 'contact@apple.com',
    action: 'DEL',
    status: 0,
    budget: 426,
    focal: 'Nguyễn Thu Lan',
    fees: 202,
    inCharge: 'Nguyễn Mạnh Trường',
  },
  {
    title: 'Mazada',
    id: '52425',
    created_date: '09-12-2014',
    description:
      'Apple Inc. is an American multinational technology company headquartered in Cupertino, California, that designs, develops, and sells consumer electronics, computer software, and online services. It is considered one of the Big Four of technology along with Amazon, Google, and Facebook',
    contact: '1 Apple Park Way, Cupertino, California, U.S.',
    phone: '0987489543',
    email: 'contact@apple.com',
    action: 'DEL',
    status: 0,
    budget: 426,
    focal: 'Nguyễn Thu Lan',
    fees: 202,
    inCharge: 'Nguyễn Mạnh Trường',
  },
  {
    title: 'Sony',
    id: '21434',
    created_date: '09-12-2014',
    description:
      'Apple Inc. is an American multinational technology company headquartered in Cupertino, California, that designs, develops, and sells consumer electronics, computer software, and online services. It is considered one of the Big Four of technology along with Amazon, Google, and Facebook',
    contact: '1 Apple Park Way, Cupertino, California, U.S.',
    phone: '0987489543',
    email: 'contact@apple.com',
    action: 'DEL',
    status: 2,
    budget: 426,
    focal: 'Nguyễn Thu Lan',
    fees: 202,
    inCharge: 'Nguyễn Mạnh Trường',
  },
  {
    title: 'Asus',
    id: '71',
    created_date: '09-12-2014',
    description:
      'Apple Inc. is an American multinational technology company headquartered in Cupertino, California, that designs, develops, and sells consumer electronics, computer software, and online services. It is considered one of the Big Four of technology along with Amazon, Google, and Facebook',
    contact: '1 Apple Park Way, Cupertino, California, U.S.',
    phone: '0987489543',
    email: 'contact@apple.com',
    action: 'DEL',
    status: 1,
    budget: 426,
    focal: 'Nguyễn Thu Lan',
    fees: 202,
    inCharge: 'Nguyễn Mạnh Trường',
  },
  {
    title: 'Intel',
    id: '21',
    created_date: '09-12-2014',
    description:
      'Apple Inc. is an American multinational technology company headquartered in Cupertino, California, that designs, develops, and sells consumer electronics, computer software, and online services. It is considered one of the Big Four of technology along with Amazon, Google, and Facebook',
    contact: '1 Apple Park Way, Cupertino, California, U.S.',
    phone: '0987489543',
    email: 'contact@apple.com',
    action: 'DEL',
    status: 1,
    budget: 426,
    focal: 'Nguyễn Thu Lan',
    fees: 202,
    inCharge: 'Nguyễn Mạnh Trường',
  },
  {
    title: 'Valve',
    id: '12',
    created_date: '09-12-2014',
    description:
      'Apple Inc. is an American multinational technology company headquartered in Cupertino, California, that designs, develops, and sells consumer electronics, computer software, and online services. It is considered one of the Big Four of technology along with Amazon, Google, and Facebook',
    contact: '1 Apple Park Way, Cupertino, California, U.S.',
    phone: '0987489543',
    email: 'contact@apple.com',
    action: 'DEL',
    status: 1,
    budget: 426,
    focal: 'Nguyễn Thu Lan',
    fees: 202,
    inCharge: 'Nguyễn Mạnh Trường',
  },
  {
    title: 'Viettel',
    id: '45',
    created_date: '09-12-2014',
    description:
      'Apple Inc. is an American multinational technology company headquartered in Cupertino, California, that designs, develops, and sells consumer electronics, computer software, and online services. It is considered one of the Big Four of technology along with Amazon, Google, and Facebook',
    contact: '1 Apple Park Way, Cupertino, California, U.S.',
    phone: '0987489543',
    email: 'contact@apple.com',
    action: 'DEL',
    status: 1,
    budget: 426,
    focal: 'Nguyễn Thu Lan',
    fees: 202,
    inCharge: 'Nguyễn Mạnh Trường',
  },
  {
    title: 'Vietcombank',
    id: '52',
    created_date: '09-12-2014',
    description:
      'Apple Inc. is an American multinational technology company headquartered in Cupertino, California, that designs, develops, and sells consumer electronics, computer software, and online services. It is considered one of the Big Four of technology along with Amazon, Google, and Facebook',
    contact: '1 Apple Park Way, Cupertino, California, U.S.',
    phone: '0987489543',
    email: 'contact@apple.com',
    action: 'DEL',
    status: 1,
    budget: 426,
    focal: 'Nguyễn Thu Lan',
    fees: 202,
    inCharge: 'Nguyễn Mạnh Trường',
  },
  {
    title: 'BIDV',
    id: '21',
    created_date: '09-12-2014',
    description:
      'Apple Inc. is an American multinational technology company headquartered in Cupertino, California, that designs, develops, and sells consumer electronics, computer software, and online services. It is considered one of the Big Four of technology along with Amazon, Google, and Facebook',
    contact: '1 Apple Park Way, Cupertino, California, U.S.',
    phone: '0987489543',
    email: 'contact@apple.com',
    action: 'DEL',
    status: 2,
    budget: 426,
    focal: 'Nguyễn Thu Lan',
    fees: 202,
    inCharge: 'Nguyễn Mạnh Trường',
  },
];

export const tradingColumns = [
  { name: 'title', title: 'Trao đổi thỏa thuận', visibility: true },
  { name: 'created_date', title: 'Được tạo từ', visibility: true },
  { name: 'budget', title: 'Ngân sách', visibility: true },
  { name: 'focal', title: 'Đầu mối', visibility: true },
  { name: 'inCharge', title: 'Phụ trách', visibility: true },
  { name: 'fees', title: 'Bổ sung thêm phí', visibility: true },
  { name: 'action', title: 'Hành động', visibility: true },
  { name: 'status', title: 'Trạng thái', visibility: true },
];

// Calendar

export const appointments = [
  {
    title: 'Website Re-Design Plan',
    startDate: new Date(2018, 5, 25, 9, 30),
    endDate: new Date(2018, 5, 25, 11, 30),
    id: 0,
    location: 'Room 1',
    priorityId: 1,
  },
  {
    title: 'Book Flights to San Fran for Sales Trip',
    startDate: new Date(2018, 5, 25, 12, 0),
    endDate: new Date(2018, 5, 25, 13, 0),
    id: 1,
    location: 'Room 1',
    priorityId: 1,
  },
  {
    title: 'Install New Router in Dev Room',
    startDate: new Date(2018, 5, 25, 14, 30),
    endDate: new Date(2018, 5, 25, 15, 30),
    id: 2,
    location: 'Room 2',
    priorityId: 1,
  },
  {
    title: 'Approve Personal Computer Upgrade Plan',
    startDate: new Date(2018, 5, 26, 10, 0),
    endDate: new Date(2018, 5, 26, 11, 0),
    id: 3,
    location: 'Room 2',
    priorityId: 1,
  },
  {
    title: 'Final Budget Review',
    startDate: new Date(2018, 5, 26, 12, 0),
    endDate: new Date(2018, 5, 26, 13, 35),
    id: 4,
    location: 'Room 2',
    priorityId: 1,
  },
  {
    title: 'New Brochures',
    startDate: new Date(2018, 5, 26, 14, 30),
    endDate: new Date(2018, 5, 26, 15, 45),
    id: 5,
    location: 'Room 2',
    priorityId: 1,
  },
  {
    title: 'Install New Database',
    startDate: new Date(2018, 5, 27, 9, 45),
    endDate: new Date(2018, 5, 27, 11, 15),
    id: 6,
    location: 'Room 1',
    priorityId: 1,
  },
  {
    title: 'Approve New Online Marketing Strategy',
    startDate: new Date(2018, 5, 27, 12, 0),
    endDate: new Date(2018, 5, 27, 14, 0),
    id: 7,
    location: 'Room 3',
  },
  {
    title: 'Upgrade Personal Computers',
    startDate: new Date(2018, 5, 27, 15, 15),
    endDate: new Date(2018, 5, 27, 16, 30),
    id: 8,
    location: 'Room 3',
    priorityId: 1,
  },
  {
    title: 'Customer Workshop',
    startDate: new Date(2018, 5, 28, 11, 0),
    endDate: new Date(2018, 5, 28, 12, 0),
    id: 9,
    location: 'Room 3',
    priorityId: 1,
  },
  {
    title: 'Prepare 2015 Marketing Plan',
    startDate: new Date(2018, 5, 28, 11, 0),
    endDate: new Date(2018, 5, 28, 13, 30),
    id: 10,
    location: 'Room 1',
    priorityId: 1,
  },
  {
    title: 'Brochure Design Review',
    startDate: new Date(2018, 5, 28, 14, 0),
    endDate: new Date(2018, 5, 28, 15, 30),
    id: 11,
    location: 'Room 2',
    priorityId: 1,
  },
  {
    title: 'Create Icons for Website',
    startDate: new Date(2018, 5, 29, 10, 0),
    endDate: new Date(2018, 5, 29, 11, 30),
    id: 12,
    location: 'Room 2',
    priorityId: 1,
  },
  {
    title: 'Upgrade Server Hardware',
    startDate: new Date(2018, 5, 29, 14, 30),
    endDate: new Date(2018, 5, 29, 16, 0),
    id: 13,
    location: 'Room 3',
    priorityId: 1,
  },
  {
    title: 'Submit New Website Design',
    startDate: new Date(2018, 5, 29, 16, 30),
    endDate: new Date(2018, 5, 29, 18, 0),
    id: 14,
    location: 'Room 3',
    priorityId: 1,
  },
  {
    title: 'Launch New Website',
    startDate: new Date(2018, 5, 29, 12, 20),
    endDate: new Date(2018, 5, 29, 14, 0),
    id: 15,
    location: 'Room 2',
    priorityId: 1,
  },
  {
    title: 'Website Re-Design Plan',
    startDate: new Date(2018, 6, 2, 9, 30),
    endDate: new Date(2018, 6, 2, 15, 30),
    id: 16,
    location: 'Room 1',
    priorityId: 1,
  },
  {
    title: 'Book Flights to San Fran for Sales Trip',
    startDate: new Date(2018, 6, 2, 12, 0),
    endDate: new Date(2018, 6, 2, 13, 0),
    id: 17,
    location: 'Room 3',
    priorityId: 1,
  },
  {
    title: 'Install New Router in Dev Room',
    startDate: new Date(2018, 6, 2, 14, 30),
    endDate: new Date(2018, 6, 2, 17, 30),
    id: 18,
    location: 'Room 2',
    priorityId: 1,
  },
  {
    title: 'Approve Personal Computer Upgrade Plan',
    startDate: new Date(2018, 6, 2, 16, 0),
    endDate: new Date(2018, 6, 3, 9, 0),
    id: 19,
    location: 'Room 2',
    priorityId: 1,
  },
  {
    title: 'Final Budget Review',
    startDate: new Date(2018, 6, 3, 10, 15),
    endDate: new Date(2018, 6, 3, 13, 35),
    id: 20,
    location: 'Room 1',
    priorityId: 1,
  },
  {
    title: 'New Brochures',
    startDate: new Date(2018, 6, 3, 14, 30),
    endDate: new Date(2018, 6, 3, 15, 45),
    id: 21,
    location: 'Room 3',
    priorityId: 1,
  },
  {
    title: 'Install New Database',
    startDate: new Date(2018, 6, 3, 15, 45),
    endDate: new Date(2018, 6, 4, 12, 15),
    id: 22,
    location: 'Room 3',
    priorityId: 1,
  },
  {
    title: 'Approve New Online Marketing Strategy',
    startDate: new Date(2018, 6, 4, 12, 35),
    endDate: new Date(2018, 6, 4, 14, 15),
    id: 23,
    location: 'Room 3',
    priorityId: 1,
  },
  {
    title: 'Upgrade Personal Computers',
    startDate: new Date(2018, 6, 4, 15, 15),
    endDate: new Date(2018, 6, 4, 20, 30),
    id: 24,
    location: 'Room 2',
    priorityId: 1,
  },
  {
    title: 'Customer Workshop',
    startDate: new Date(2018, 6, 5, 6, 0),
    endDate: new Date(2018, 6, 5, 14, 20),
    id: 25,
    location: 'Room 1',
    priorityId: 1,
  },
  {
    title: 'Customer Workshop',
    startDate: new Date(2018, 6, 5, 14, 35),
    endDate: new Date(2018, 6, 5, 16, 20),
    id: 26,
    location: 'Room 1',
    priorityId: 1,
  },
  {
    title: 'Customer Workshop 2',
    startDate: new Date(2018, 6, 5, 10, 0),
    endDate: new Date(2018, 6, 5, 11, 20),
    id: 27,
    location: 'Room 2',
    priorityId: 1,
  },
  {
    title: 'Prepare 2015 Marketing Plan',
    startDate: new Date(2018, 6, 5, 20, 0),
    endDate: new Date(2018, 6, 6, 13, 30),
    id: 28,
    location: 'Room 3',
    priorityId: 1,
  },
  {
    title: 'Brochure Design Review',
    startDate: new Date(2018, 6, 6, 14, 10),
    endDate: new Date(2018, 6, 6, 15, 30),
    id: 29,
    location: 'Room 3',
    priorityId: 1,
  },
  {
    title: 'Create Icons for Website',
    startDate: new Date(2018, 6, 6, 10, 0),
    endDate: new Date(2018, 6, 7, 14, 30),
    id: 30,
    location: 'Room 1',
    priorityId: 1,
  },
  {
    title: 'Upgrade Server Hardware',
    startDate: new Date(2018, 6, 3, 9, 30),
    endDate: new Date(2018, 6, 3, 12, 25),
    id: 31,
    location: 'Room 2',
    priorityId: 1,
  },
  {
    title: 'Submit New Website Design',
    startDate: new Date(2018, 6, 3, 12, 30),
    endDate: new Date(2018, 6, 3, 18, 0),
    id: 32,
    location: 'Room 2',
    priorityId: 1,
  },
  {
    title: 'Launch New Website',
    startDate: new Date(2018, 6, 3, 12, 20),
    endDate: new Date(2018, 6, 3, 14, 10),
    id: 33,
    location: 'Room 2',
    priorityId: 1,
  },
  {
    title: 'Book Flights to San Fran for Sales Trip',
    startDate: new Date(2018, 5, 26, 0, 0),
    endDate: new Date(2018, 5, 27, 0, 0),
    id: 34,
    location: 'Room 1',
    priorityId: 1,
  },
  {
    title: 'Customer Workshop',
    startDate: new Date(2018, 5, 29, 10, 0),
    endDate: new Date(2018, 5, 30, 14, 30),
    id: 35,
    location: 'Room 1',
    priorityId: 1,
  },
  {
    title: 'Google AdWords Strategy',
    startDate: new Date(2018, 6, 3, 0, 0),
    endDate: new Date(2018, 6, 4, 10, 30),
    id: 36,
    location: 'Room 3',
    priorityId: 1,
  },
  {
    title: 'Rollout of New Website and Marketing Brochures',
    startDate: new Date(2018, 6, 5, 10, 0),
    endDate: new Date(2018, 6, 9, 14, 30),
    id: 37,
    location: 'Room 3',
    priorityId: 1,
  },
  {
    title: 'Update NDA Agreement',
    startDate: new Date(2018, 6, 1, 10, 0),
    endDate: new Date(2018, 6, 3, 14, 30),
    id: 38,
    location: 'Room 2',
    priorityId: 1,
  },
  {
    title: 'Customer Workshop',
    startDate: new Date(2018, 6, 1),
    endDate: new Date(2018, 6, 2),
    allDay: true,
    id: 39,
    location: 'Room 1',
    priorityId: 1,
  },
];

export const priorities = [
  {
    id: 0,
    title: 'Low',
  },
  {
    id: 1,
    title: 'Medium',
  },
  {
    id: 2,
    title: 'High',
  },
];

// template
export const templateRows = [
  {
    title: 'Niêm yết',
    template_type: 'Biểu mẫu bảo hành',
    id: '1425',
    created_date: '20-10-2018',
  },
  {
    title: 'Thoái vốn',
    template_type: 'Biểu mẫu hóa đơn',
    id: '1253',
    created_date: '20-10-2018',
  },
  {
    title: 'Đơn dài hạn',
    template_type: 'Biểu mẫu bảo hành',
    id: '1266',
    created_date: '20-10-2018',
  },
  {
    title: 'Hợp đồng',
    template_type: 'Biểu mẫu hóa đơn',
    id: '1276',
    created_date: '20-10-2018',
  },
  {
    title: 'Hóa đơn bán hàng mẫu',
    template_type: 'Biểu mẫu hóa đơn',
    id: '129',
    created_date: '20-10-2018',
  },
];

export const templateColumns = [
  { name: 'title', title: 'Tiêu đề', visibility: true },
  { name: 'template_type', title: 'Loại văn bản', visibility: true },
  { name: 'created_date', title: 'Ngày tạo', visibility: true },
];

// template type
export const templateTypeRows = [
  {
    title: 'Biểu mẫu biên bản bàn giao',
    code: 'BMBBBG',
    id: '1425',
    status: 'Luôn sử dụng',
  },
  {
    title: 'Biểu mẫu báo giá',
    code: 'BMBG',
    id: '1253',
    status: 'Luôn sử dụng',
  },
  {
    title: 'Biểu mẫu bảo hành',
    code: 'BMBH',
    id: '1266',
    status: 'Luôn sử dụng',
  },
  {
    title: 'Biểu mẫu hóa đơn',
    code: 'BMHD',
    id: '1276',
    status: 'Luôn sử dụng',
  },
  {
    title: 'Biểu mẫu hợp đồng',
    code: 'BMHD',
    id: '129',
    status: 'Luôn sử dụng',
  },
];

export const templateTypeColumns = [
  { name: 'title', title: 'Tiêu đề', visibility: true },
  { name: 'code', title: 'Mã', visibility: true },
  { name: 'status', title: 'Trạng thái', visibility: true },
];

// Expenses

export const expensesRows = [
  {
    title: 'Biểu mẫu biên bản bàn giao',
    code: 'BMBBBG',
    id: '1425',
    status: 'Chưa sử dụng',
    created_by: 'Nguyễn Văn Minh',
  },
  {
    title: 'Biểu mẫu báo giá',
    code: 'BMBG',
    id: '1253',
    status: 'Chưa sử dụng',
    created_by: 'Nguyễn Văn Minh',
  },
  {
    title: 'Biểu mẫu bảo hành',
    code: 'BMBH',
    id: '1266',
    status: 'Chưa sử dụng',
    created_by: 'Nguyễn Văn Minh',
  },
  {
    title: 'Biểu mẫu hóa đơn',
    code: 'BMHD',
    id: '1276',
    status: 'Chưa sử dụng',
    created_by: 'Nguyễn Văn Minh',
  },
  {
    title: 'Biểu mẫu hợp đồng',
    code: 'BMHD',
    id: '129',
    status: 'Chưa sử dụng',
    created_by: 'Nguyễn Văn Minh',
  },
];

export const expensesColumns = [
  { name: 'title', title: 'Nhu cầu / Trao đổi', visibility: true },
  { name: 'code', title: 'Mã dự toán', visibility: true },
  { name: 'created_by', title: 'Người tạo', visibility: true },
  { name: 'status', title: 'Trạng thái', visibility: true },
];

// Expenses detail

export const expensesDetailRows = [
  {
    title: 'Sản xuất bàn ghế phòng họp',
    code: 'BMBBBG',
    unit: '1425',
    price: 'Nguyễn Văn Minh',
    quantity: 12,
    vat: 10,
    note: 'Không có gì',
    amount: 146,
  },
];

export const expensesDetailColumns = [
  { name: 'title', title: 'Tên hạng mục diễn giải', visibility: true },
  { name: 'code', title: 'Mã số', visibility: true },
  { name: 'unit', title: 'Đơn vị tính', visibility: true },
  { name: 'price', title: 'Đơn giá', visibility: true },
  { name: 'quantity', title: 'Số lượng', visibility: true },
  { name: 'vat', title: 'VAT', visibility: true },
  { name: 'amount', title: 'Thành tiền', visibility: true },
  { name: 'note', title: 'Ghi chú', visibility: true },
];

// Chính sách bán hàng
export const rowsSale = [
  {
    title: 'Giảm giá',
    id: '21',
    start_date: '09-03-2019',
    end_date: '09-04-2019',
    rule_type: 'Giảm giá đơn giản',
    status: 'Hoạt động',
  },
  {
    title: 'Giảm giá mặt hàng nhà bếp',
    id: '11',
    start_date: '04-08-2018',
    end_date: '03-09-2018',
    rule_type: 'Giảm giá cao cấp',
    status: 'Không hoạt động',
  },
];

export const columnsSale = [
  { name: 'id', title: 'ID', visibility: true },
  { name: 'title', title: 'Tên quy tắc', visibility: true },
  { name: 'start_date', title: 'Ngày bắt đầu', visibility: true },
  { name: 'end_date', title: 'Ngày kết thúc', visibility: true },
  { name: 'rule_type', title: 'Loại quy tắc', visibility: true },
  { name: 'status', title: 'Tình trạng', visibility: true, data: { type: 'SALE_POLICY' } },
];

export const customers = [
  { label: 'NGUYEN VAN A', value: 1 },
  { label: 'NGUYEN VAN B', value: 2 },
  { label: 'NGUYEN VAN C', value: 3 },
  { label: 'NGUYEN VAN D', value: 4 },
  { label: 'NGUYEN VAN E', value: 5 },
  { label: 'NGUYEN VAN F', value: 6 },
];

// Phê duyệt động

export const rowsApproved = [
  {
    title: 'Nhóm công việc phòng kinh doanh',
    id: '21',
    stage: 'Báo giá',
    employees: 'Hỗ trợ Lifetek',
  },
  {
    title: 'Nhóm tài chính',
    id: '11',
    stage: 'Chuyển kho',
    employees: 'Nguyễn Văn Bình',
  },
];

export const columnsApproved = [
  { name: 'id', title: 'ID', visibility: true },
  { name: 'title', title: 'Tên nhóm', visibility: true },
  { name: 'stage', title: 'Công đoạn', visibility: true },
  { name: 'employees', title: 'Nhân viên', visibility: true },
];
